version: "3.7"

services:
  db:
    build:
      context: .
    container_name: webapi-mvc-db
    restart: unless-stopped
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    volumes:
      - webapi-mvc:/var/lib/postgresql/data

volumes:
  webapi-mvc: